#!/usr/bin/env python3
"""Turn a CSV of difficulty ratings into one SQL statement.

The `difficulty` column is only ever written at capture, so every
activity created before it existed is un-rated and sorts last under the
Difficulty sort — and appears in none of the three smart lists. This is
the one-off that fixes that. See "Guessing how hard it is" in CLAUDE.md.

Usage:
    python3 tools/difficulty-backfill.py ratings.csv > backfill.sql

Then paste backfill.sql into the Supabase SQL editor.

The CSV needs an id column and a difficulty column; everything else is
ignored, so an export straight out of the Activities table works as-is
once a rating column has been added to it. Header names are matched
case-insensitively and any of these are accepted:

    id          id, activity_id, uuid
    difficulty  difficulty, diff, rating, tier

Values are lower-cased and must be easy / medium / hard. Anything else
is reported and skipped rather than guessed at — a wrong rating files
an activity into the wrong smart list, and the whole point of the three
lists is that their contents can be trusted.

The output is a single UPDATE ... FROM (VALUES ...) so the whole
backfill is one statement and one transaction: it either all lands or
none of it does. It writes only rows whose difficulty is still null, so
re-running it cannot overwrite a rating the app has since inferred, and
running it twice is harmless.
"""
import csv, sys, re, collections

ID_KEYS   = ('id', 'activity_id', 'uuid')
DIFF_KEYS = ('difficulty', 'diff', 'rating', 'tier')
TIERS     = ('easy', 'medium', 'hard')
UUID_RE   = re.compile(r'^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$', re.I)


def pick(fieldnames, wanted):
    lookup = {(f or '').strip().lower(): f for f in fieldnames}
    for w in wanted:
        if w in lookup:
            return lookup[w]
    return None


def main(path):
    with open(path, newline='', encoding='utf-8-sig') as fh:
        rows = list(csv.DictReader(fh))
    if not rows:
        sys.exit('empty csv')

    id_col   = pick(rows[0].keys(), ID_KEYS)
    diff_col = pick(rows[0].keys(), DIFF_KEYS)
    if not id_col or not diff_col:
        sys.exit(f'need an id column {ID_KEYS} and a difficulty column {DIFF_KEYS}; '
                 f'found {list(rows[0].keys())}')

    pairs, skipped = [], collections.Counter()
    seen = set()
    for i, r in enumerate(rows, 2):          # 2 = first data line, counting the header
        rid  = (r.get(id_col)   or '').strip()
        diff = (r.get(diff_col) or '').strip().lower()
        if not rid:
            skipped['no id'] += 1;                            continue
        if not UUID_RE.match(rid):
            skipped[f'line {i}: not a uuid ({rid!r})'] += 1;  continue
        if diff not in TIERS:
            skipped[f'line {i}: bad rating ({diff!r})'] += 1;  continue
        if rid in seen:
            skipped[f'line {i}: duplicate id'] += 1;          continue
        seen.add(rid)
        pairs.append((rid, diff))

    for why, n in skipped.items():
        print(f'-- skipped: {why}' + (f' x{n}' if n > 1 else ''), file=sys.stderr)
    if not pairs:
        sys.exit('nothing to write')
    print(f'-- {len(pairs)} rows, {len(skipped)} skipped', file=sys.stderr)

    # Ids are uuid-validated and tiers are from a fixed set, so neither
    # can carry a quote; this is not string-concatenated user input.
    values = ',\n  '.join(f"('{rid}'::uuid, '{diff}')" for rid, diff in pairs)
    print(f"""-- Backfill difficulty ratings. {len(pairs)} rows.
-- Generated by tools/difficulty-backfill.py — do not hand-edit.
-- Requires supabase/difficulty.sql to have been run first.
--
-- `difficulty is null` is the guard: this only fills in blanks, so it
-- cannot overwrite a rating the app has inferred since the export, and
-- running it a second time is a no-op.
update "Activities" a
   set difficulty = v.difficulty
  from (values
  {values}
) as v(id, difficulty)
 where a.id = v.id
   and a.difficulty is null;""")


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
